comp<-read.csv(file.choose())
View(comp)
dummies <- fastDummies::dummy_cols(comp)
comp1<-dummies[-c(1,7,8,9,12,14,16)]
windows()
pairs(comp1)
cor(comp1)
install.packages("GGally")
install.packages("stringi")
install.packages("ggplot2")
library(GGally)
library(caTools)
set.seed(123)
Split<-sample.split(comp1$price,SplitRatio=0.7)
comp.train <- subset(comp1,Split == TRUE)
comp.test<-subset(comp1,Split== FALSE)
model<-lm(price~.,data=comp.train)
summary(model)
library(car)
comp_train<-as.numeric(comp.train)
avPlots(model)
comp.train[1:10] <- lapply(comp.train[1:10], as.numeric)
influence.measures(model)
influenceIndexPlot(model,id.n=5)
influencePlot(model,id.n=5)
windows()
library(VIF)
vif(model)
library(car)
influenceIndexPlot(model1,id.n=3)
influencePlot(model1)
model1<-lm(price ~ log(speed) + log(hd) + ram +screen +ads+cd_yes+multi_yes+trend+premium_yes, data = comp.train)
summary(model1)
mean(model1$residuals)
plot(model$residuals)
hist
sqrt(mean(model1$residuals^2))
plot(model1)
hist(model$residuals)
predict_test<-predict(model1,comp.test)
error<-comp.test$price-predict_test
mean(error)
hist(error)
mean(comp$price)
sqrt(mean(error^2))

