fraud<-read.csv(file.choose())
View(fraud)
str(fraud)
status<-ifelse(fraud$Taxable.Income>=30000,"Good","Risky")
fraud<-data.frame(fraud,status)
fraud_final<-fraud[,-3]
library(cartools)
library(caTools)
install.packages("tree")
library(tree)
split_tag<-sample.split(fraud_final$status,SplitRatio=0.7)
train<-subset(fraud_final,split_tag==T)
test<-subset(fraud_final,split_tag==F)
tree_model<-tree(status~.,data=train)
summary(tree_model)
plot(tree_model)
text(tree_model,pretty=0)
tree_pred<-predict(tree_model,test,type="class")
confusion<-table(test$status,tree_pred)
acc<-sum(diag(confusion))/sum(confusion)
acc
confusion
cv_tree<-cv.tree(tree_model,FUN=prune.misclass)
cv_tree
plot(cv_tree)
pruned_model<-prune.misclass(tree_model,best=3)
plot(pruned_model)
text(pruned_model,pretty=0)
tree_pred1<-predict(pruned_model,test,type="class")
confusion<-table(test$sale,tree_pred1)
confusion
Acc<-sum(diag(confusion))/sum(confusion)
Acc
