sales<-read.csv(file.choose())
View(sales)
str(sales)
sale<-ifelse(sales$Sales>=10,"high","low")
sales<-data.frame(sales,sale)
sales_final<-sales[,-1]
library(cartools)
library(caTools)
#install.packages("tree")
library(tree)
split_tag<-sample.split(sales_final$sale,SplitRatio=0.7)
train<-subset(sales_final,split_tag==T)
test<-subset(sales_final,split_tag==F)
tree_model<-tree(sale~.,data=train)
summary(tree_model)
plot(tree_model)
text(tree_model,pretty=0)
tree_pred<-predict(tree_model,test,type="class")
confusion<-table(test$sale,tree_pred)
acc<-sum(diag(confusion))/sum(confusion)
acc
confusion
cv_tree<-cv.tree(tree_model,FUN=prune.misclass)
cv_tree
plot(cv_tree)
pruned_model<-prune.misclass(tree_model,best=5)
plot(pruned_model)
text(pruned_model,pretty=0)
tree_pred1<-predict(pruned_model,test,type="class")
confusion<-table(test$sale,tree_pred1)
confusion
Acc<-sum(diag(confusion))/sum(confusion)
Acc
